image: node

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - bash .scripts/build.sh
  cache:
    policy: push
    paths:
      - server/
      - public/
      - node_modules/

test:
  stage: test
  when: on_success
  script:
    - bash .scripts/test.sh
  cache:
    paths:
      - server/
      - public/

deploy:
  stage: deploy
  when: on_success
  only:
    - develop
    - feature/NJE-98
    - feature/NJE-99
  script:
    - bash .scripts/deploy.sh
  cache:
    policy: pull
    paths:
      - server/
      - public/
