export const FETCH_BOARDS = 'FETCH_BOARDS';
export const SAVE_BOARDS_TO_STORE = 'SAVE_BOARDS_TO_STORE';
export const SAVE_BOARDS_ERROR = 'SAVE_BOARDS_ERROR';

export const FETCH_BOARD = 'FETCH_BOARD';
export const SAVE_BOARD_TO_STORE = 'SAVE_BOARD_TO_STORE';
