export const FETCH_TICKETS = 'FETCH_TICKETS';
export const SAVE_TICKETS_TO_STORE = 'SAVE_TICKETS_TO_STORE';
export const CREATE_TICKET = 'CREATE_TICKET';
export const UPDATE_TICKET = 'UPDATE_TICKET';
export const DELETE_TICKET = 'DELETE_TICKET';
