export const SET_BOARDS_ERROR = 'SET_BOARDS_ERROR';
export const SET_TICKETS_ERROR = 'SET_TICKETS_ERROR';

export const SHOW_EDIT_BOARD_MODAL = 'SHOW_EDIT_BOARD_MODAL';
export const HIDE_EDIT_BOARD_MODAL = 'HIDE_EDIT_BOARD_MODAL';
export const UPDATE_EDIT_BOARD_MODAL_DATA = 'UPDATE_EDIT_BOARD_MODAL_DATA';

export const SHOW_DELETE_BOARD_MODAL = 'SHOW_DELETE_BOARD_MODAL';
export const HIDE_DELETE_BOARD_MODAL = 'HIDE_DELETE_BOARD_MODAL';
